---
title: "A tour of tidypandas"
date: "`r Sys.Date()`"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# you might need to set the virtualenv correctly in the next line
reticulate::use_virtualenv("~/.cache/pypoetry/virtualenvs/tidypandas-cfuMUHaV-py3.8/"
                           , required = TRUE
                           )
```

# A tour of `tidypandas`

----

> The intent of this document is to illustrate some standard data manipulation exercises
 using [`tidypandas`](https://github.com/talegari/tidypandas) python package. We use the `nycflights13` data.

----
 
> [`tidypandas`](https://github.com/talegari/tidypandas) -- A **grammar of data manipulation** for [pandas](https://pandas.pydata.org/docs/index.html) inspired by [tidyverse](https://tidyverse.tidyverse.org/)

----

`nycflights13` contains information about all flights that departed from NYC (e.g. EWR, JFK and LGA) to destinations in the United States, Puerto Rico, and the American Virgin Islands) in 2013: 336,776 flights in total. To help understand what causes delays, it also includes a number of other useful datasets.
    
  - flights: all flights that departed from NYC in 2013
  - weather: hourly meteorological data for each airport
  - planes: construction information about each plane
  - airports: airport names and locations
  - airlines: translation between two letter carrier codes and names

## Imports

```{python}
from tidypandas import tidyframe
from tidypandas.series_utils import *
from plotnine import *

# for plotnine: some column need downcasting from nullable types
def downcast_dtypes(pdf):
    from pandas.api import types
    cn = list(pdf.columns)
    pdf2 = pdf.copy()
    for acolname in cn:
        if types.is_numeric_dtype(pdf[acolname]):
            pdf2[acolname] = pd.to_numeric(pdf2[acolname].astype('string'), downcast = 'integer')
    return pdf2
```

## Load and Display `flights` data

```{python}
from nycflights13 import flights, planes
flights_tidy = tidyframe(flights)
print(flights_tidy)
```


## Exercise: Find all flights that arrived more than two hours late, but didn’t leave late.

```{python}
out = (flights_tidy.filter("dep_delay <= 0 and arr_delay > 120")
                   .select(['flight', 'dep_delay', 'arr_delay'])
                   )
print(out)
```
## Exercise: Sort flights to find the fastest flights

```{python}
out = (flights_tidy.mutate({'speed': (lambda x, y: x/y, ['distance', 'air_time'])})
                   .arrange([('speed', 'desc')])
                   .select(['flight', 'dep_delay', 'arr_delay', 'speed'])
                   )
print(out)
```

## Exercise: Is the proportion of cancelled flights related to the average delay?


```{python}
out = (flights_tidy
        .mutate({'cancelled': (lambda x, y: (pd.isna(x) | pd.isna(y)),
                               ['arr_delay', 'dep_delay']
                              )
                }
               )
        .summarise({'cancelled_prop': (np.mean, 'cancelled'),
                    'avg_dep_delay': (np.mean, 'dep_delay'),
                    'avg_arr_delay': (np.mean, 'arr_delay')
                   },
                   by = ['year', 'month', 'day']
                  )
        )
                        
print(out)
```



```{python}
data_for_plot = (out.pivot_longer(cols = ['avg_dep_delay', 'avg_arr_delay'],
                                  names_to = "delay_type"
                                  )
                    )
print(data_for_plot)

(ggplot(downcast_dtypes(data_for_plot.to_pandas()),
        aes('value', 'cancelled_prop', color = 'delay_type')
        ) +
    geom_point() +
    geom_smooth(method = "lm")
    )
```

## Exercise: Find all destinations that are flown by at least two carriers. Use that information to rank the carriers.

```{python}
out = (flights_tidy.mutate({'n_carriers': (n_distinct, 'carrier')}, by = 'dest')
                   .filter('n_carriers > 1')
                   .summarise({'n_dest': (n_distinct, 'dest')}, by = 'carrier')
                   .arrange([('n_dest', 'desc')])
                   )
print(out)
```


## Exercise: Is there a relationship between the age of a plane and its delays?

```{python}
planes_tidy = tidyframe(planes)
print(planes_tidy)

planes_year_frame = (planes_tidy.select(['tailnum', 'year'])
                                .rename({'year': 'plane_year'})
                                )
print(planes_year_frame)

age_delay_stats_frame = \
  (flights_tidy.inner_join(planes_year_frame, on = 'tailnum')
               .mutate({'age': (lambda x, y: x - y, ['year', 'plane_year'])})
               .filter(lambda x: ~ pd.isna(x['age']))
               .mutate({'age_25': lambda x: ifelse(x['age'] > 25, 25, x['age'])})
               .summarise(column_names = ['arr_delay', 'dep_delay'],
                          func = np.mean,
                          prefix = 'mean_',
                          by = 'age'
                          )
               )
print(age_delay_stats_frame)

(ggplot(age_delay_stats_frame.to_pandas().pipe(downcast_dtypes), aes('age', 'mean_arr_delay')) +
     geom_point() +
     xlim(0, 20) +
     ylim(0, 11)
     )
```